@echo off
echo Installing Django...
pip install -r requirements.txt

echo Creating database migrations...
python manage.py makemigrations

echo Applying migrations...
python manage.py migrate

echo Creating superuser (optional - press Ctrl+C to skip)...
python manage.py createsuperuser

echo Starting development server...
python manage.py runserver